status/payment/urls.py
from django.urls import path
from .views import view_orders, process_payment, confirm_payment, enter_payment_amount,get_payment,view_payments
app_name = 'payment'
urlpatterns = [
    path('orders/', view_orders, name='orders'),
    path('process_payment/', process_payment, name='process_payment'),
    path('confirm_payment/', confirm_payment, name='confirm_payment'),
    path('enter_payment_amount/', enter_payment_amount, name='enter_payment_amount'),
    path('get_payment/',get_payment,name='get_payment'),
    path('view_payments',view_payments,name='view_payments'),
    #path('',,name=''),
    #path('',,name=''),
    #path('',,name=''),
    #path('',,name=''),
    #path('',,name=''),
]

status/status/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from registering import views

urlpatterns = [
    path('i18n/',include('django.conf.urls.i18n')),
    
]
urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('registering/',include('registering.urls')),
    path('documents/',include('documents.urls')),
    path('payment/',include('payment.urls')),
    path('change-language/<str:lang>/', views.change_language, name='change_language'),  # إض
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

status/users/urls.py
from django.urls import path
from .views import person_in,main,parent_save,parent_in,index,user_is_logined,person_show,partner_in,assert_information,get_choice,death_record,person_save,add_person_information,add_marrid,add_divorce,add_widower,death_save,event_in,died_person_record,information_save,person_is_here,about

app_name = 'users'
urlpatterns = [

    path('person_in', person_in,name='person_in'),
    path('parent_save', parent_save,name='parent_save'),
    path('main', main,name='main'),
    path('parent_in', parent_in,name='parent_in'),
    path('index', index,name='index'),
    path('user_is_logined', user_is_logined,name='user_is_logined'),
    path('person_show',person_show ,name='person_show'),
    path('partner_in', partner_in,name='partner_in'),
    path('add_person_information',add_person_information ,name='add_person_information'),
    path('assert_information',assert_information ,name='assert_information'),
    path('get_choice',get_choice ,name='get_choice'),
    path('death_record',death_record ,name='death_record'),
    path('person_save', person_save,name='person_save'),
    path('add_marrid', add_marrid,name='add_marrid'),
    path('add_divorce', add_divorce,name='add_divorce'),
    path('add_widower', add_widower,name='add_widower'),
    path('death_save',death_save ,name='death_save'),
    path('event_in', event_in,name='event_in'),
    path('died_person_record',died_person_record ,name='died_person_record'),
    path('information_save',information_save ,name='information_save'),
    path('person_is_here', person_is_here,name='person_is_here'),
    path('about',about ,name='about'),
    #path('', ,name=''),
    #path('', ,name=''),
    #path('', ,name=''),

]

status/payment/models.py
from django.db import models
from django.contrib.auth.models import User

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=20)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order {self.id} by {self.user.username} - Status: {self.status}"

class Payment(models.Model):
    user = models.CharField(max_length=15,blank=True,null=True)
    transaction_id = models.CharField(max_length=100, unique=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2,blank=True,null=True)
    status = models.CharField(max_length=20, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Payment {self.transaction_id} - Amount: {self.amount} - Status: {self.status}"

class Balance(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"balnce {self.user.username} - is : {self.balance}"

status/payment/views.py
from django.shortcuts import render, redirect
from .models import Order, Payment, Balance
from documents.models import Document
from django.contrib.auth.models import User

def view_orders(request):
    error = ''
    orders = Order.objects.filter(user=request.user,status ='Pending')
    if not Balance.objects.filter(user=request.user).exists():
        Balance(user=request.user,balance=0).save()
    balance = Balance.objects.get(user=request.user)
    if request.method == "POST":
        selected_order_ids = request.POST.getlist('selected_orders')
        orders = Order.objects.filter(id__in=selected_order_ids)
        total_cost = sum(order.cost for order in orders)
        if total_cost > int(balance.balance) :
            error ='you do not have enough'
        else :
            balance.balance = int(balance.balance) - total_cost
            balance.save()
            for order in orders:
                order.status ='paid'
                order.save()
                document = Document.objects.get(code=order.code)
                document.paid = 'paid'
                document.save()
            orders = Order.objects.filter(user=request.user,status ='Pending')
    return render(request, 'payment/view_orders.html', {'orders': orders,'balance':balance,'error':error})

def process_payment(request):
    if request.method == "POST":
        selected_order_ids = request.POST.getlist('selected_orders')
        orders = Order.objects.filter(id__in=selected_order_ids)
        total_cost = sum(order.cost for order in orders)
        return render(request, 'payment/payment_page.html', {'total_cost': total_cost, 'orders': orders})

def get_payment(request):
    error = ''
    if request.method == "POST":
        transaction_id = request.POST.get('payment_reference')
        if Payment.objects.filter(transaction_id=transaction_id,status='proccessed').exists():
            payment = Payment.objects.get(transaction_id=transaction_id)
        else :
            payment = Payment(user=request.user,transaction_id=transaction_id)
        try :
            payment.save()
            error = 'the payment saved'
        except :
            error = 'try anathor transaction id'
    return render(request, 'payment/payment_page.html',{'error':error})


def view_payments(request):
    error = ''
    payments = Payment.objects.filter(user=request.user)
    if not payments.exists():
        error = 'you have no payments to show'
    return render(request, 'payment/view_payments.html', {'payments': payments,'error':error})



def confirm_payment(request):
    if request.method == "POST":
        total_cost = request.POST.get('total_cost')
        payment_reference = request.POST.get('payment_reference')
        selected_order_ids = request.POST.getlist('selected_orders')

        # Logic to deduct from user's balance and update orders
        # Here you might check the user's profile for balance

        Order.objects.filter(id__in=selected_order_ids).update(status='Paid')
        return redirect('view_orders')  # Redirect to success page

def enter_payment_amount(request):
    error = ''
    if request.method == "POST":
        transaction_id = request.POST.get('transaction_id')
        amount = request.POST.get('amount')
        status = 'proccessed'
        try:
            if Payment.objects.filter(transaction_id=transaction_id,status=status).exists():
                error = 'Transaction ID is already exist'
            else:
                if Payment.objects.filter(transaction_id=transaction_id).exists():
                    payment = Payment.objects.get(transaction_id=transaction_id)
                    payment.amount = amount
                    payment.status = status
                    user_id = User.objects.get(username=payment.user).id
                    balance = Balance.objects.get(user=user_id)
                    balance.balance = int(balance.balance) + int(amount)
                    balance.save()
                else :
                    payment = Payment(amount=amount,transaction_id=transaction_id,status=status)
                payment.save()
                error = ' the payment saved'
        except Payment.DoesNotExist:
            return render(request, 'payment/enter_payment_amount.html', {'error': 'Transaction ID not found!'})
    return render(request, 'payment/enter_payment_amount.html', {'error': error})

status/templates/payment/enter_payment_amount.html
<!DOCTYPE html>
<html lang="en">

    {% load i18n %}

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/paymentstyle.css' %}">
    <title>{% trans "Enter Payment Amount"%}</title>
</head>

<body>
    <div class="container">
        <h1>{% trans "Enter Payment Amount"%}</h1>
        {% if error %}
        <p style="color:red;">{{ error }}</p>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="payment-item">
                <input type="text" name="transaction_id" style ="margin:10px;" placeholder="{% trans 'Enter transaction id'%}" required>
                <input type="number" name="amount" style ="margin:10px;" placeholder="{% trans 'Enter Amount'%}" required>
            </div>
            <button type="submit">{% trans "Save Payments"%}</button>
        </form>
    </div>
</body>

</html>

status/templates/payment/payment_page.html
<!DOCTYPE html>
<html lang="en">

    {% load i18n %}
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/paymentstyle.css' %}">
    <title>{% trans "Payment"%}</title>
</head>
<body>
    <div class="container">
        <h1>{% trans "Payment"%}</h1>
        {{error}}
        <form method="post" action="">
            {% csrf_token %}
            <input type="hidden" name="total_cost" value="{{ total_cost }}">
            <input type="text" name="payment_reference" placeholder="{% trans 'Enter Payment Reference'%}" required>
            <button type="submit">{% trans "Confirm Payment"%}</button>
        </form>
        <button onclick="goBack()">back</button>

    </div>
    <script>
        function goBack() {
            window.location.href = "{% url 'payment:orders' %}";
    }
    </script>
</body>
</html>

status/templates/payment/view_orders.html
{% extends "pages/sidebar.html" %}

    {% load i18n %}
{% load static %}
{%block titleside%}
    <link rel="stylesheet" href="{% static 'css/paymentstyle.css' %}">
    <title>{% trans "Your Orders"%}</title>
    <script>
        function updateTotalCost() {
            const checkboxes = document.querySelectorAll('input[name="selected_orders"]');
            const balance = parseFloat(document.getElementById('user-balance').innerText);
            let totalCost = 0;

            checkboxes.forEach(checkbox => {
                if (checkbox.checked) {
                    const cost = parseFloat(checkbox.getAttribute('data-cost'));
                    totalCost += cost;
                }
            });

            document.getElementById('total-cost').innerText = totalCost.toFixed(2);

            checkboxes.forEach(checkbox => {
                const cost = parseFloat(checkbox.getAttribute('data-cost'));
                if (totalCost + cost > balance && !checkbox.checked) {
                    checkbox.disabled = true;
                } else {
                    checkbox.disabled = false;
                }
            });
        }
    </script>
{% endblock titleside %}
{% block contentside %}
    <div class="container">
        <h1>{% trans "Your Orders"%}</h1>
        <h2 >{{ request.user.username }} {% trans "balance is"%} <span id="user-balance">{{ balance.balance }}</span></h2>
        <h2>{% trans "Total Cost"%}: <span id="total-cost">0.00</span></h2>
        {% if error %}
            <p style="color: red;">{{ error }}</p>
        {% endif %}
        <form method="post" action="">
            {% csrf_token %}
            {% for order in orders %}
                <div class="order-item">
                    <input type="checkbox" name="selected_orders" value="{{ order.id }}" data-cost="{{ order.cost }}" onclick="updateTotalCost()">
                    <span>{{ order }} - Cost: {{ order.cost }} - Status: {{ order.status }}</span>
                </div>
            {% endfor %}
            <button type="submit">{% trans "Proceed to Payment"%}</button>
        </form>
        <a href="{% url 'payment:get_payment' %}"><button>{% trans "Pay"%}</button></a>
    </div>
    {% endblock contentside%}

status/templates/payment/view_payments.html
<!DOCTYPE html>
<html lang="en">
    {% load i18n %}
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/paymentstyle.css' %}">
    <title>{% trans "Your payments"%}</title>
</head>
<body>
    {{error}}
    <div class="container">
        <h1>{% trans "Your payments"%}</h1>
        <form method="post" action="">
            {% csrf_token %}
            {% for payment in payments %}
                <div class="payment-item">
                    <span>{{ payment }}</span>
                </div>
            {% endfor %}
        </form>
        <a href="{% url 'users:main' %}"><button> {% trans "cancel"%} </button></a>
    </div>
    <script>
    </script>
</body>
</html>