status/documents/urls.py
from django.urls import path
from .views import family_register,send_email_view,death_register,marriage_register,birth_register,show_marriage_register,divorce_register,choose_document,get_document,show_documents,review_task,send_notes,done_task,insert_document,insert_task,refuse_with_note,death_register_show,show_new_documents,delete_document
app_name = 'documents'
urlpatterns = [

    path('family_register',family_register ,name='family_register'),
    path('send_email_view',send_email_view ,name='send_email_view'),
    path('death_register',death_register ,name='death_register'),
    path('marriage_register',marriage_register ,name='marriage_register'),
    path('birth_register',birth_register ,name='birth_register'),
    path('show_marriage_register',show_marriage_register ,name='show_marriage_register'),
    path('divorce_register', divorce_register,name='divorce_register'),
    path('choose_document', choose_document,name='choose_document'),
    path('get_document', get_document,name='get_document'),
    path('show_documents', show_documents,name='show_documents'),
    path('review_task',review_task,name='review_task'),
    path('send_notes', send_notes,name='send_notes'),
    path('done_task', done_task,name='done_task'),
    path('insert_document',insert_document ,name='insert_document'),
    path('insert_task', insert_task,name='insert_task'),
    path('refuse_with_note',refuse_with_note ,name='refuse_with_note'),
    path('death_register_show', death_register_show,name='death_register_show'),
    path('show_new_documents', show_new_documents,name='show_new_documents'),
    path('delete_document', delete_document,name='delete_document'),
    #path('', ,name=''),
    #path('', ,name=''),
    #path('', ,name=''),
    #path('', ,name=''),
    #path('', ,name=''),
    #path('', ,name=''),

]

status/status/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from registering import views

urlpatterns = [
    path('i18n/',include('django.conf.urls.i18n')),
    
]
urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('registering/',include('registering.urls')),
    path('documents/',include('documents.urls')),
    path('payment/',include('payment.urls')),
    path('change-language/<str:lang>/', views.change_language, name='change_language'),  # إض
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

status/users/urls.py
from django.urls import path
from .views import person_in,main,parent_save,parent_in,index,user_is_logined,person_show,partner_in,assert_information,get_choice,death_record,person_save,add_person_information,add_marrid,add_divorce,add_widower,death_save,event_in,died_person_record,information_save,person_is_here,about

app_name = 'users'
urlpatterns = [

    path('person_in', person_in,name='person_in'),
    path('parent_save', parent_save,name='parent_save'),
    path('main', main,name='main'),
    path('parent_in', parent_in,name='parent_in'),
    path('index', index,name='index'),
    path('user_is_logined', user_is_logined,name='user_is_logined'),
    path('person_show',person_show ,name='person_show'),
    path('partner_in', partner_in,name='partner_in'),
    path('add_person_information',add_person_information ,name='add_person_information'),
    path('assert_information',assert_information ,name='assert_information'),
    path('get_choice',get_choice ,name='get_choice'),
    path('death_record',death_record ,name='death_record'),
    path('person_save', person_save,name='person_save'),
    path('add_marrid', add_marrid,name='add_marrid'),
    path('add_divorce', add_divorce,name='add_divorce'),
    path('add_widower', add_widower,name='add_widower'),
    path('death_save',death_save ,name='death_save'),
    path('event_in', event_in,name='event_in'),
    path('died_person_record',died_person_record ,name='died_person_record'),
    path('information_save',information_save ,name='information_save'),
    path('person_is_here', person_is_here,name='person_is_here'),
    path('about',about ,name='about'),
    #path('', ,name=''),
    #path('', ,name=''),
    #path('', ,name=''),

]

status/users/views.py
from django.shortcuts import render,redirect
import documents
from .forms import TaskPerson_in,Partner_in,Parent_in,Dead_in
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from .models import Person,Marrid,Dead,Divorce,TaskPerson,Widower
from documents.models import Document
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.core.mail import send_mail
from django.utils.translation import gettext_lazy as _
from django.core.mail import BadHeaderError
import smtplib
import csv

def move_person(tasked_person):
    new_object_data = {
        'person_name' : tasked_person.person_name,
        'national_num' : tasked_person.national_num,
        'first_name' : tasked_person.first_name,
        'last_name' : tasked_person.last_name,
        'dad_name' : tasked_person.dad_name,
        'national_dad' : tasked_person.national_dad,
        'mom_name' : tasked_person.mom_name,
        'national_mom' : tasked_person.national_mom,
        'birth_place' : tasked_person.birth_place,
        'birth_date' : tasked_person.birth_date,
        'date_of_issue' : tasked_person.date_of_issue,
        'place_of_issue' : tasked_person.place_of_issue,
        'number_of_issue' : tasked_person.number_of_issue,
        'religion' : tasked_person.religion,
        'gender' : tasked_person.gender,
        'status' : tasked_person.status,
        'image' : tasked_person.image,
        }
    person = Person.objects.create(**new_object_data)
    return person

def move_tasked_person(tasked_person):
    new_object_data = {
        'person_name' : tasked_person.person_name,
        'national_num' : tasked_person.national_num,
        'first_name' : tasked_person.first_name,
        'last_name' : tasked_person.last_name,
        'dad_name' : tasked_person.dad_name,
        'national_dad' : tasked_person.national_dad,
        'mom_name' : tasked_person.mom_name,
        'national_mom' : tasked_person.national_mom,
        'birth_place' : tasked_person.birth_place,
        'birth_date' : tasked_person.birth_date,
        'date_of_issue' : tasked_person.date_of_issue,
        'place_of_issue' : tasked_person.place_of_issue,
        'number_of_issue' : tasked_person.number_of_issue,
        'religion' : tasked_person.religion,
        'gender' : tasked_person.gender,
        'status' : tasked_person.status,
        'image' : tasked_person.image,
        }
    person = TaskPerson.objects.create(**new_object_data)
    return person

def person_is_here(request):

        page_name = 'person who not in the data base'
        name = user_is_logined(request=request)
        if Person.objects.filter(person_name=name).exists() :
            return redirect('users:main')
        else:
            if TaskPerson.objects.filter(person_name=name).exists() :
                person = TaskPerson.objects.filter(person_name=name).last()
                choices = ['add personal information','show new documents','pay for orders','show payments']
                return render(request,'pages/main_new.html',{'emperson':person,'choices':choices,'page_name':page_name})
            else:
                return redirect('users:add_person_information')



def add_person_information(request):
        user_is_logined(request)
        person_name=user_is_logined(request)
        error=' '
        task_name = 'add information'
        if request.method == "POST":
            data = TaskPerson_in(request.POST,request.FILES)
            if data.is_valid():
                national_num = request.POST['national_num']
                data.save()
                person_s = TaskPerson.objects.get(national_num = national_num,code=None)
                person_s.person_name = person_name
                person_s.save()
                request.session['task_name'] = task_name
                code = documents.views.insert_task_code(request)
                person_s.code = code
                person_s.save()
                request.session['document_code'] = code
                return redirect('users:person_is_here')
            else:
                error = data.errors
        if Person.objects.filter(person_name=person_name).exists():
            person = Person.objects.get(person_name=person_name)
            return render(request,'users/person_in.html',{'emperson':person,'person':TaskPerson_in,'error':error,'task_name':task_name})
        else :
            return render(request,'users/person_in_new.html',{'person':TaskPerson_in,'error':error,'task_name':task_name})

def person_in(request):

        name = user_is_logined(request=request)
        if Person.objects.filter(person_name=name).exists():
            person = Person.objects.get(person_name=name)
        else :
            return redirect ('users:person_is_here')
        error=' '
        task_name = 'add person'
        if request.method == "POST":
            data = TaskPerson_in(request.POST,request.FILES)
            if data.is_valid():
                national_num = request.POST['national_num']
                data.save()
                Person_s = TaskPerson.objects.get(national_num = national_num,code=None)
                national_num = Person_s.national_num
                request.session['task_name'] = task_name
                request.session['second_national_num'] = national_num
                code = documents.views.insert_task_code(request)
                Person_s.code = code
                Person_s.save()
                request.session['document_code'] = code
                return redirect('users:main')
            else:
                error = data.errors
        return render(request,'users/person_in.html',{'emperson':person,'person':TaskPerson_in,'error':error,'task_name':task_name})



def person_save(request):
        name = user_is_logined(request=request)
        if Person.objects.filter(person_name=name).exists():
            person = Person.objects.get(person_name=name)
        else :
            return redirect ('users:person_is_here')
        error=' '
        task_name = 'save person'
        document_code = request.session.get('document_code','0')
        document = Document.objects.get(code=document_code)
        second_national_num = document.second_national_num
        if Person.objects.filter(national_num=second_national_num).exists():
            person_added_exist = Person.objects.get(national_num=second_national_num)
            person_name = person_added_exist.person_name
            if person_name != None :
                error = 'the asked person can not modify'
        else :
             person_name = 'No one'
        tasked_person_added = TaskPerson.objects.get(code=document_code)
        if request.method == "POST":
            if person_name == None :
                person_added_exist.delete()
            person_added = move_person(tasked_person_added)
            person_added.save()
            tasked_person_added.delete()
            document.done = True
            document.save()
            error = 'the person had been saved succefully'
        return render(request,'users/person_save.html',{'emperson':person,'person':tasked_person_added,'error':error,'task_name':task_name})



def information_save(request):

        name = user_is_logined(request=request)
        if Person.objects.filter(person_name=name).exists():
            person = Person.objects.get(person_name=name)
        else :
            return redirect ('users:person_is_here')
        error=' '
        task_name = 'save person information'
        document_code = request.session.get('document_code','0')
        document = Document.objects.get(code=document_code)
        person_national_num = document.person_national_num
        tasked_person_added = TaskPerson.objects.get(code=document_code)
        tasked_person_added_name =tasked_person_added.person_name
        if request.method == "POST":
            if Person.objects.filter(national_num=person_national_num).exists():
                past_person = Person.objects.get(national_num=person_national_num)
                past_person.delete()
            if Person.objects.filter(person_name=tasked_person_added_name).exists():
                past_person = Person.objects.get(person_name=tasked_person_added_name)
                past_person.delete()
            person_added = move_person(tasked_person_added)
            person_added.save()
            tasked_person_added.delete()
            document.done = True
            document.save()
            error = _("Data saved successfully!")
        return render(request,'users/person_save.html',{'emperson':person,'person':tasked_person_added,'error':error,'task_name':task_name})



def get_by_obj(national_num):
    if Person.objects.filter(national_num = national_num).exists() :
        user = Person.objects.get(national_num = national_num)
    else :
        user = Person.objects.get(national_num = '00000000000')
    return user

def user_is_logined(request):
    if request.user.is_authenticated:
        name = request.user.username
        return name
    else :
        return redirect ('registering:CustomLoginView')

def get_marrid(person):
    marrid_partner=[]
    if person.gender == 'male':
        partners = Marrid.objects.filter(national_hus=person.national_num)
        if len(partners) !=0:
            for partner in partners :
                marrid_partner.append(Person.objects.get(national_num=partner.national_wife))
    else :
        partners = Marrid.objects.filter(national_wife=person.national_num)
        if len(partners) !=0:
            for partner in partners :
                marrid_partner.append(Person.objects.get(national_num=partner.national_hus))
    return marrid_partner

def get_divorce(person):
    divorce_partner=[]
    if person.gender == 'male':

status/templates/users/died_person.html
{% extends "pages/sidebar.html" %}
{% load i18n %}
{%block titleside%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
    rel="stylesheet"
	        integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
	        crossorigin="anonymous">
    <title> {{task_name}}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
        .grid-container {
            display: grid;
            grid-template-columns: repeat(auto-fill, 1fr);
            gap: 10px;
        }
        .grid-item {
            background-color: #f0f0f0;
            padding: 10px;
            border: 1px solid #ccc;
            text-align: center;
        }
        .show{
            padding: 10px;
            border: 1px solid #ccc;
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 10px;
            align-items: center;
        }
        .image_show{
            padding: 10px;
            border: 1px solid #ccc;
            display: grid;
            grid-template-columns: repeat(1, 1fr);
            gap: 10px;
            align-items: center;
        }
    </style>
{% endblock titleside%}
{% block contentside %}
    {{error}}
    <div class="column" style="width: 100%;">
    <form method="POST"  enctype="multipart/form-data">
            <p>{% trans "welcome"%} {{person_name}}</p>
            <div class = "column" >
                <div class="show">
                    {%csrf_token%}
                    <div class = "col-6">{% trans "national id for the dead"%}  : </div><div class = "col-6">{{died.national_num}}</div>
                    <div class = "col-6">{% trans "date of the death"%} : </div><div class = "col-6"> {{died.date_of_event}}</div>
                    <div class = "col-6">{% trans "place of the death"%} : </div><div class = "col-6">{{died.place_of_event}}</div>
                    {% if not died.image.url %}
                    <div class = "col-6">{% trans "image"%} : </div><div class = "col-6"> {{died.image}}</div>
                    {% endif %}
                </div>
                <input type="submit" value="save">
            </div>
        </form>
        <div  class="image_show">
            {% if died.image.url %}
            <div><img src="{{ died.image.url }}" alt="صورة المستخدم"></div>
            {% endif %}
        </div>

        {% if error ==  'please assert a person first' %}
        <div>
            <a href="{% url 'users:died_person_record'%}"><button>{% trans "insert dead person"%}</button>  </a>
        </div>
        {% endif %}
        <button onclick="goBack()">{% trans "Cancel"%}</button>
    </div>
<script>

        function goBack() {
            window.history.back();
        }
        </script>
{% endblock contentside%}

status/templates/users/partner.html
{% extends "pages/sidebar.html" %}
{% load i18n %}
{%block titleside%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
    rel="stylesheet"
	        integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
	        crossorigin="anonymous">
    <title> task_name</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
        .grid-container {
            display: grid;
            grid-template-columns: repeat(auto-fill, 1fr);
            gap: 10px;
        }
        .grid-item {
            background-color: #f0f0f0;
            padding: 10px;
            border: 1px solid #ccc;
            text-align: center;
        }
        .show{
            padding: 10px;
            border: 1px solid #ccc;
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 10px;
            align-items: center;
        }
        .image_show{
            padding: 10px;
            border: 1px solid #ccc;
            display: grid;
            grid-template-columns: repeat(1, 1fr);
            gap: 10px;
            align-items: center;
        }
    </style>
{% endblock titleside%}
{% block contentside %}
    {{error}}
    <div class="column"  style="width: 100%;">
        <p>{% trans "welcome"%} {{person_name}}</p>
        {% trans "please assert your event information"%}
    <form method="POST"  enctype="multipart/form-data">
            <div class = "column">
                <div class="show">
                    {%csrf_token%}
                    <div class = "col-6">{% trans "national ID"%} : </div><div class = "col-6">{{event.partner_national_num}}</div>
                    <div class = "col-6">{% trans "event type"%} : </div><div class = "col-6"> {{event.marrid}}</div>
                    <div class = "col-6">{% trans "event date"%} : </div><div class = "col-6">{{event.date_of_event}}</div>
                    <div class = "col-6">{% trans "event place"%} : </div><div class = "col-6">{{event.place_of_event}}</div>
                    <div class = "col-6">{% trans "image"%} : </div><div class = "col-6">{{event.image}}</div>
                </div>
                <input type="submit" value="save">
            </div>
        </form>
        <div  class="image_show">
            {% if partner.image.url %}
            <div>
                <img src="{{ partner.image.url }}" alt="صورة المستخدم">
            </div>
            {% endif %}
        </div>
        {% if error ==  'please assert a person first' %}
        <div>
            <a href="{% url 'users:partner_in'%}"><button>{% trans "insert partner"%}</button>  </a>
        </div>
        {% endif %}
        <button onclick="goBack()">{% trans "Cancel"%}</button>
    </div>

    <script>
        function goBack() {
            window.history.back();
        }
        </script>
{% endblock contentside%}

status/templates/users/partner_save.html
{% extends "pages/sidebar.html" %}
{% load i18n %}
{%block titleside%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
    rel="stylesheet"
	        integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
	        crossorigin="anonymous">
    <title> {{task_name}}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
        .grid-container {
            display: grid;
            grid-template-columns: repeat(auto-fill, 1fr);
            gap: 10px;
        }
        .grid-item {
            background-color: #f0f0f0;
            padding: 10px;
            border: 1px solid #ccc;
            text-align: center;
        }
        .show{
            padding: 10px;
            border: 1px solid #ccc;
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 10px;
            align-items: center;
        }
        .image_show{
            padding: 10px;
            border: 1px solid #ccc;
            display: grid;
            grid-template-columns: repeat(1, 1fr);
            gap: 10px;
            align-items: center;
        }
    </style>
{% endblock titleside%}
{% block contentside %}
    {{error}}
    <div class="column" style="width: 100%;">
    <form method="POST"  enctype="multipart/form-data">
            <div class = "column">
                <div class="show">
                    {%csrf_token%}
                    <div class = "col-6">{% trans "first name"%} : </div><div class = "col-6">{{person.first_name}}</div>
                    <div class = "col-6">{% trans "last name"%} : </div><div class = "col-6"> {{person.last_name}}</div>
                    <div class = "col-6">{% trans "national id"%} : </div><div class = "col-6">{{person.national_num}}</div>
                    <div class = "col-6">{% trans "dad name"%} : </div><div class = "col-6"> {{person.dad_name}}</div>
                    <div class = "col-6">{% trans "dad national id"%} : </div><div class = "col-6">{{person.national_dad}}</div>
                    <div class = "col-6">{% trans "mom name"%} : </div><div class = "col-6"> {{person.mom_name}}</div>
                    <div class = "col-6">{% trans "mom national id"%} : </div><div class = "col-6">{{person.national_mom}}</div>
                    <div class = "col-6">{% trans "birth place"%} : </div><div class = "col-6">{{person.birth_place}}</div>
                    <div class = "col-6">{% trans "birth date"%} : </div><div class = "col-6">{{person.birth_date}}</div>
                    <div class = "col-6">{% trans "place of issue"%} : </div><div class = "col-6">{{person.place_of_issue}}</div>
                    <div class = "col-6">{% trans "number of issue"%} : </div><div class = "col-6">{{person.number_of_issue}}</div>
                    <div class = "col-6">{% trans "religion"%} :  </div><div class = "col-6">{{person.religion}}</div>
                    <div class = "col-6">{% trans "gender"%} :  </div><div class = "col-6">{{person.gender}}</div>
                    <div class = "col-6">{% trans "status"%} :  </div><div class = "col-6">{{person.status}}</div>
                    <div class = "col-6">{% trans "date of event"%} :  </div><div class = "col-6">{{person.date_of_event}}</div>
                    <div class = "col-6">{% trans "place of event"%} :  </div><div class = "col-6">{{person.place_of_event}}</div>
                    <div class = "col-6">{% trans "image"%} : </div><div class = "col-6"> {{person.image}}</div>
                </div>
                {% if error != 'the person had been saved succefully' %}
                {% if error in ['the person who asked not inserted his informations',"there\'re no relation between the person and the dead person"] %}
                <input type="submit" value="save">
                {% endif %}
                <a href="{% url 'documents:refuse_with_note' %}"><button> {% trans "refuse with note"%} </button></a>
                {% endif %}
            </div>
            </form>
            <div  class="image_show">
                {% if person.image.url %}
                <div>
                    <img src="{{ person.image.url }}" alt="صورة المستخدم">
                </div>
                {% endif %}
            </div>
            {% if error == 'the person had been saved succefully' %}
            <a href="{% url 'documents:show_documents' %}"><button> {% trans "go back"%} </button></a>
            {% else %}
            <button onclick="goBack()">{% trans "Cancel"%}</button>
            {% endif %}
        </div>

    <script>
        function goBack() {
            window.history.back();
        }
        </script>
{% endblock contentside%}

status/templates/users/person_save.html
{% extends "pages/sidebar.html" %}
{% load i18n %}
{%block titleside%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
    rel="stylesheet"
	        integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
	        crossorigin="anonymous">
    <title> {{task_name}}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
        .grid-container {
            display: grid;
            grid-template-columns: repeat(auto-fill, 1fr);
            gap: 10px;
        }
        .grid-item {
            background-color: #f0f0f0;
            padding: 10px;
            border: 1px solid #ccc;
            text-align: center;
        }
        .show{
            padding: 10px;
            border: 1px solid #ccc;
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 10px;
            align-items: center;
        }
        .image_show{
            padding: 10px;
            border: 1px solid #ccc;
            display: grid;
            grid-template-columns: repeat(1, 1fr);
            gap: 10px;
            align-items: center;
        }
    </style>
{% endblock titleside%}
{% block contentside %}
    {{error}}
    <div class="column"style="width: 100%;">
    <form method="POST"  enctype="multipart/form-data">
            <div class = "column">
                <div class="show">
                    {%csrf_token%}
                    <div class = "col-6">{% trans "first name"%} : </div><div class = "col-6">{{person.first_name}}</div>
                    <div class = "col-6">{% trans "last name"%} : </div><div class = "col-6"> {{person.last_name}}</div>
                    <div class = "col-6">{% trans "national id"%} : </div><div class = "col-6">{{person.national_num}}</div>
                    <div class = "col-6">{% trans "dad name"%} : </div><div class = "col-6"> {{person.dad_name}}</div>
                    <div class = "col-6">{% trans "dad national id"%} : </div><div class = "col-6">{{person.national_dad}}</div>
                    <div class = "col-6">{% trans "mom name"%} : </div><div class = "col-6"> {{person.mom_name}}</div>
                    <div class = "col-6">{% trans "mom national id"%} : </div><div class = "col-6">{{person.national_mom}}</div>
                    <div class = "col-6">{% trans "birth place"%} : </div><div class = "col-6">{{person.birth_place}}</div>
                    <div class = "col-6">{% trans "birth date"%} : </div><div class = "col-6">{{person.birth_date}}</div>
                    <div class = "col-6">{% trans "place of issue"%} : </div><div class = "col-6">{{person.place_of_issue}}</div>
                    <div class = "col-6">{% trans "number of issue"%} : </div><div class = "col-6">{{person.number_of_issue}}</div>
                    <div class = "col-6">{% trans "religion"%} :  </div><div class = "col-6">{{person.religion}}</div>
                    <div class = "col-6">{% trans "gender"%} :  </div><div class = "col-6">{{person.gender}}</div>
                    <div class = "col-6">{% trans "status"%} :  </div><div class = "col-6">{{person.status}}</div>
                    <div class = "col-6">{% trans "date of issue"%} : </div><div class = "col-6">{{person.date_of_issue}}</div>
                </div>
                {% if error != 'the person had been saved succefully' %}
                {% if error != 'the asked person can not modify' %}
                <input type="submit" value="save">
                {% endif %}
                <a href="{% url 'documents:refuse_with_note' %}"><button> {% trans "refuse with note"%} </button></a>
                {% endif %}
            </div>
            </form>
            <div  class="image_show">
                {% if person.image %}
                <div>
                    <img src="{{ person.image.url }}" alt="صورة المستخدم">
                </div>
                {% endif %}
            </div>
            {% if error == 'Data saved successfully!' %}
            <a href="{% url 'documents:show_documents' %}"><button> {% trans "go back"%} </button></a>
            {% else %}
            <button onclick="goBack()">{% trans "Cancel"%}</button>
            {% endif %}
        </div>

    <script>
        function goBack() {
            window.history.back();
        }
        </script>
{% endblock contentside%}