status/documents/urls.py
from django.urls import path
from .views import family_register,send_email_view,death_register,marriage_register,birth_register,show_marriage_register,divorce_register,choose_document,get_document,show_documents,review_task,send_notes,done_task,insert_document,insert_task,refuse_with_note,death_register_show,show_new_documents,delete_document
app_name = 'documents'
urlpatterns = [

    path('family_register',family_register ,name='family_register'),
    path('send_email_view',send_email_view ,name='send_email_view'),
    path('death_register',death_register ,name='death_register'),
    path('marriage_register',marriage_register ,name='marriage_register'),
    path('birth_register',birth_register ,name='birth_register'),
    path('show_marriage_register',show_marriage_register ,name='show_marriage_register'),
    path('divorce_register', divorce_register,name='divorce_register'),
    path('choose_document', choose_document,name='choose_document'),
    path('get_document', get_document,name='get_document'),
    path('show_documents', show_documents,name='show_documents'),
    path('review_task',review_task,name='review_task'),
    path('send_notes', send_notes,name='send_notes'),
    path('done_task', done_task,name='done_task'),
    path('insert_document',insert_document ,name='insert_document'),
    path('insert_task', insert_task,name='insert_task'),
    path('refuse_with_note',refuse_with_note ,name='refuse_with_note'),
    path('death_register_show', death_register_show,name='death_register_show'),
    path('show_new_documents', show_new_documents,name='show_new_documents'),
    path('delete_document', delete_document,name='delete_document'),
    #path('', ,name=''),
    #path('', ,name=''),
    #path('', ,name=''),
    #path('', ,name=''),
    #path('', ,name=''),
    #path('', ,name=''),

]

status/status/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from registering import views

urlpatterns = [
    path('i18n/',include('django.conf.urls.i18n')),
    
]
urlpatterns += i18n_patterns(
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('registering/',include('registering.urls')),
    path('documents/',include('documents.urls')),
    path('payment/',include('payment.urls')),
    path('change-language/<str:lang>/', views.change_language, name='change_language'),  # إض
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

status/users/urls.py
from django.urls import path
from .views import person_in,main,parent_save,parent_in,index,user_is_logined,person_show,partner_in,assert_information,get_choice,death_record,person_save,add_person_information,add_marrid,add_divorce,add_widower,death_save,event_in,died_person_record,information_save,person_is_here,about

app_name = 'users'
urlpatterns = [

    path('person_in', person_in,name='person_in'),
    path('parent_save', parent_save,name='parent_save'),
    path('main', main,name='main'),
    path('parent_in', parent_in,name='parent_in'),
    path('index', index,name='index'),
    path('user_is_logined', user_is_logined,name='user_is_logined'),
    path('person_show',person_show ,name='person_show'),
    path('partner_in', partner_in,name='partner_in'),
    path('add_person_information',add_person_information ,name='add_person_information'),
    path('assert_information',assert_information ,name='assert_information'),
    path('get_choice',get_choice ,name='get_choice'),
    path('death_record',death_record ,name='death_record'),
    path('person_save', person_save,name='person_save'),
    path('add_marrid', add_marrid,name='add_marrid'),
    path('add_divorce', add_divorce,name='add_divorce'),
    path('add_widower', add_widower,name='add_widower'),
    path('death_save',death_save ,name='death_save'),
    path('event_in', event_in,name='event_in'),
    path('died_person_record',died_person_record ,name='died_person_record'),
    path('information_save',information_save ,name='information_save'),
    path('person_is_here', person_is_here,name='person_is_here'),
    path('about',about ,name='about'),
    #path('', ,name=''),
    #path('', ,name=''),
    #path('', ,name=''),

]

status/documents/models.py
from django.db import models
from datetime import datetime

class Document(models.Model):
    name = models.CharField(max_length=15)
    code = models.CharField(max_length=15)
    person_national_num = models.CharField(max_length=15)
    second_national_num = models.CharField(max_length=15,null=True,blank=True)
    document_date = models.DateTimeField(default=datetime.now)
    viewed = models.BooleanField(default=False)
    done = models.BooleanField(default=False)
    paid = models.CharField(max_length=15,default='not paid')
    notes = models.TextField(null=True,blank=True)

    def __str__(self):
        return self.name
    

status/documents/forms.py
from django import forms
from .models import Document
from django.core.exceptions import ValidationError


class Send_notes(forms.ModelForm):
    class Meta :
        model = Document
        fields = ['notes']



class Death_register(forms.Form):
    national_dead = forms.CharField(max_length=15)

    def clean_national_num(self):
        data = self.cleaned_data['national_partner']
        if not data.startswith('0') or len(data)!=11 :
            raise ValidationError('error')
        return str(data)

status/documents/views.py
from django.shortcuts import render,redirect
from users.views import get_family,get_marrid,get_first_relation,user_is_logined,get_divorce,main,person_is_here
from users.models import Person,Marrid,Divorce,Dead,TaskPerson
from .forms import Death_register,Send_notes
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Document
from datetime import datetime
from django.contrib import messages
from django.http import HttpResponse
from payment.models import Order
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


def send_email_view(request):
    if request.method == 'POST':
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        recipient_list = [request.POST.get('email')]

        try:
            print('1')
            print(settings.DEFAULT_FROM_EMAIL)
            send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, recipient_list)
            messages.success(request, 'تم إرسال البريد الإلكتروني بنجاح!')
            return redirect('family_doc')  # استبدلها بالعنوان URL المطلوب
        except Exception as e:
            er = messages.error(request, f'حدث خطأ: {e}')
            print(er)

    return render(request, 'mail/mail.html')

def get_person(request):
        name = user_is_logined(request=request)
        try :
            document_code = request.session.get('document_code','0')
            document = Document.objects.get(code=document_code)
            person_national_num =document.person_national_num
            if Person.objects.filter(national_num=person_national_num).exists() :
                person = Person.objects.get(national_num=person_national_num)
            elif TaskPerson.objects.filter(national_num=person_national_num).exists() :
                person = TaskPerson.objects.get(national_num=person_national_num,code=None)
        except:
            if Person.objects.filter(person_name=name).exists() :
                person = Person.objects.get(person_name=name)
            elif TaskPerson.objects.filter(person_name=name).exists() :
                person = TaskPerson.objects.get(person_name=name,code=None)
        return person

def refuse_with_note(request):

        name = user_is_logined(request=request)
        if Person.objects.filter(person_name=name).exists():
            person = Person.objects.get(person_name=name)
        else :
            return redirect ('users:person_is_here')
        error = ''
        task_name = 'refuse with note'
        if request.method == "POST":
            data = Send_notes(request.POST)
            if data.is_valid():
                notes = request.POST['notes']
                code = request.session.get('document_code','0')
                document = Document.objects.get(code=code)
                document_notes = document.notes
                notes = notes + '\n' + name + '   ' + str(datetime.now()) + '\n'
                document_notes = document_notes + notes
                document.notes = document_notes
                document.document_date = str(datetime.now())
                document.viewed = True
                document.save()
                return redirect('documents:show_documents')
            else :
                error = data.errors
        return render(request,'documents/note.html',{'emperson':person,'form':Send_notes,'error':error,'task_name':task_name})

def send_notes(request):

        name = user_is_logined(request=request)
        if Person.objects.filter(person_name=name).exists():
            person = Person.objects.get(person_name=name)
        elif TaskPerson.objects.filter(person_name=name).exists():
            person = TaskPerson.objects.filter(person_name=name).last()
        else :
            return redirect ('users:person_is_here')
        error = ''
        task_name = 'add note'
        if request.method == "POST":
            data = Send_notes(request.POST)
            if data.is_valid():
                notes = request.POST['notes']
                code = request.session.get('document_code','0')
                document = Document.objects.get(code=code)
                document_notes = document.notes
                notes = notes + '\n' + name + '   ' + str(datetime.now()) + '\n'
                document_notes = document_notes + notes
                document.notes = document_notes
                document.document_date = str(datetime.now())
                document.viewed = False
                document.save()
                messages.success(request, _("Data saved successfully!"))
                return redirect('documents:review_task')
            else :
                error = data.errors
        return render(request,'documents/note.html',{'emperson':person,'form':Send_notes,'error':error,'task_name':task_name})

def family_register(request):

        name = user_is_logined(request=request)
        if Person.objects.filter(person_name=name).exists():
            emperson = Person.objects.get(person_name=name)
        else :
            return redirect ('users:person_is_here')
        person = get_person(request=request)
        employee = person
        task_name = 'family register'
        event = False
        if person.status == 'single':
            national_num = person.national_dad
            try :
                person = Person.objects.get(national_num = national_num)
            except:
                 return HttpResponse('please assert your dad first to get family register')
        national_num = person.national_num
        family = get_family(national_num=national_num)
        request.session['task_name'] = task_name
        return render(request,'documents/confirm_family.html',{'emperson':emperson,'person':person,'family':family,'task_name':task_name,'event':event,'employee':employee})


def birth_register(request):

        name = user_is_logined(request=request)
        if Person.objects.filter(person_name=name).exists():
            emperson = Person.objects.get(person_name=name)
        else :
            return redirect ('users:person_is_here')
        person = get_person(request=request)
        task_name = 'birth register'
        event = False
        request.session['task_name'] = task_name
        employee = person
        return render(request,'documents/confirm_person.html',{'emperson':emperson,'person':person,'task_name':task_name,'event':event,'employee':employee})



def show_marriage_register(request):

        name = user_is_logined(request=request)
        if Person.objects.filter(person_name=name).exists():
            emperson = Person.objects.get(person_name=name)
        else :
            return redirect ('users:person_is_here')
        family = []
        person = get_person(request=request)
        national_num = request.GET.get('national_num')
        if national_num is None :
            code = request.session.get('document_code','0')
            document = Document.objects.get(code=code)
            national_num = document.second_national_num
        partner_national_num = national_num
        partner = Person.objects.get(national_num=partner_national_num)
        if person.gender == 'male':
            husband = person
            wife = partner
        else :
            husband = person
            wife = partner
        if partner in get_marrid(person):
            task_name = 'marriage'
            request.session['task_name'] = 'marriage register'
            event = Marrid.objects.get(national_wife=wife.national_num)
        if partner in get_divorce(person):
            task_name = 'divorce'
            divorce_times = Divorce.objects.filter(national_wife=wife.national_num)
            request.session['task_name'] = 'divorce register'
            for time in divorce_times :
                if time.national_hus == person.national_num :
                    event = time
        family.append(husband)
        family.append(wife)
        request.session['second_national_num'] = wife.national_num
        employee = person
        return render(request,'documents/confirm_family.html',{'emperson':emperson,'person':person,'family':family,'task_name':task_name,'event':event,'employee':employee})



def marriage_register(request):

        name = user_is_logined(request=request)
        if Person.objects.filter(person_name=name).exists():
            emperson = Person.objects.get(person_name=name)
        else :
            return redirect ('users:person_is_here')
        person = get_person(request=request)
        family = []
        if person.gender == 'male':
            task_name = 'all marriage'
        marrid_member = get_marrid(person)
        for user in marrid_member :
            family.append(user)
        if person.gender == 'female':
            task_name = 'marriage register'
        return render(request,'documents/show_all.html',{'emperson':emperson,'person':person,'family':family,'task_name':task_name})



def divorce_register(request):

        name = user_is_logined(request=request)
        if Person.objects.filter(person_name=name).exists():
            emperson = Person.objects.get(person_name=name)
        else :
            return redirect ('users:person_is_here')
        person = get_person(request=request)
        divorce_group = []
        if person.gender == 'male':
            task_name = 'divorce all'
        divorce_member = get_divorce(person)
        for user in divorce_member :
            divorce_group.append(user)
        if person.gender == 'female':
            task_name = 'divorce register'
        request.session['task_name'] = 'divorce register'
        return render(request,'documents/show_all.html',{'emperson':emperson,'person':person,'family':divorce_group,'task_name':task_name})



def death_register_show(request):

status/templates/documents/choose_document.html
{% extends "pages/sidebar.html" %}

{%block titleside%}
    <title>{{page_name}}</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        .card{
            border: 2px;
            padding: 3%;
            width: 75%;
            border: 1px solid #ccc;
            margin: 5%;
            cursor: pointer;
        }
    </style>
{% endblock titleside %}


{% block contentside %}

<div class="column" >
<div class="documents-container">
    {% for document in documents %}
        <div class="card"
            data-name="{{ document }}" >
            <h3>{{ document }}</h3>
        </div>
    {% endfor %}
</div>
<button onclick="goBack()">Cancel</button>

 </div>


<script>
    function goBack() {
        window.history.back();
    }
    $(document).ready(function(){
        $('.card').on('click', function() {
            var name = $(this).data('name');

            $.ajax({
                url: "{% url 'documents:get_document' %}",
                type: "POST",
                data: {
                    'name': name,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    window.location.href = response.url;
                },
                error: function(xhr) {
                    alert('حدث خطأ: ' + xhr.responseText);
                }
            });
        });
    });
</script>

{% endblock contentside%}

status/templates/documents/confirm_family.html
{% extends "pages/sidebar.html" %}
{% load i18n %}
{%block titleside%}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
    crossorigin="anonymous">
<title>{{task_name}}</title>
<style>
    .grid-container {
        display: grid;
        grid-template-columns: repeat(auto-fill,  1fr);
        gap: 10px;
    }
    .grid-item {
        background-color: #f0f0f0;
        padding: 10px;
        border: 1px solid #ccc;
        text-align: center;
    }
    .show{
        padding: 10px;
        border: 1px solid #ccc;
        display: grid;
        grid-template-columns: repeat(9, 1fr);
    }
    .first{
        padding: 10px;
        border: 1px solid #ccc;
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 10px;
    }#dataf{
        width :100%;
        border:1px solid #000;
        padding :10px;
    }
    #datan{
        width :15vw;
        border:1px solid #000;
        padding :10px;
    }
    #data{
        width :8vw;
        border:1px solid #000;
        padding :10px;
    }

    #dataf *{
        margin:10px;
    }

    #datan *{
        margin:10px;
    }

    #data *{
        margin:10px;
    }

</style>
{%endblock titleside %}

{%block contentside %}
    <div class="column ">
    <p>{% trans "welcome"%} {{person.person_name}}</p>
    <form method="POST" style=" overflow :auto;  max-width:100%; width:95%;  padding: 10px; border: 1px solid #ccc;display: grid; grid-template-columns: repeat(1, 1fr);gap: 10px;" enctype="multipart/form-data">
        {%csrf_token%}

    <div class = "column">
        <div class="first">
            <div id="dataf" class = "col-12">{% trans "place of issue"%} :  {{person.place_of_issue}} </div>
            <div id="dataf" class = "col-12">{% trans "number of issue"%} :  {{person.number_of_issue}} </div>
        </div>
        <div class="show" >
            <div id="datan" class = "col-12 row-2"><div class = "row"> {% trans "name"%}  </div> <div class = "row"> {% trans "national number"%} </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {% trans "sur name"%} </div> <div class = "row">  </div></div>
            <div id="datan" class = "col-12 row-2"><div class = "row"> {% trans "dad name"%} </div> <div class = "row"> {% trans "national number"%} </div></div>
            <div id="datan" class = "col-12 row-2"><div class = "row"> {% trans "mom name"%} </div> <div class = "row"> {% trans "national number"%} </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {% trans "date and"%}  </div> <div class = "row"> {% trans "place birth"%} </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {% trans "religion"%} </div> <div class = "row">  </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {% trans "gender"%} </div> <div class = "row">  </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {% trans "status"%} </div> <div class = "row">  </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {% trans "date issue"%} </div> <div class = "row">   </div></div>
        </div>

        {% for person in family %}
        <div class="show">
            <div id="datan" class = "col-12 row-2"><div class = "row"> {{person.first_name}} </div> <div class = "row">{{person.national_num}}</div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {{person.last_name}} </div> <div class = "row"></div></div>
            <div id="datan" class = "col-12 row-2"><div class = "row"> {{person.dad_name}}</div> <div  class = "row">{{person.national_dad}}</div></div>
            <div id="datan" class = "col-12 row-2"><div class = "row"> {{person.mom_name}} </div> <div class = "row">{{person.national_mom}}</div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {{person.birth_place}}  </div><div class = "row">{{person.birth_date|date:"y-m-d"}} </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {{person.religion}} </div><div class = "row"></div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {{person.gender}} </div><div class = "row"></div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {{person.status}} </div><div class = "row"></div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {{person.date_of_issue}} </div><div class = "row"></div></div>
        </div>
        {% endfor %}
    </div>
</form>
<div >
{% if employee.is_employee %}
<a  style="margin: 1%;" href="{% url 'documents:refuse_with_note' %}" class="btn btn-primary">{% trans "refuse with note"%}</a>
<button style="margin: 1%;" onclick="donePage()"> {{task_name}} {% trans "is done"%}</button>
<button style="margin: 1%;" onclick="printPage()">{% trans "print" %}{{task_name}}</button>
{% else %}
<a  style="margin: 1%;" href="{% url 'documents:insert_task' %}" class="btn btn-primary">{% trans "get"%} {{task_name}}</a>
{% endif %}
<button onclick="goBack()">{% trans "Cancel"%}</button>
</div>
</div>
<script>

    function goBack() {
        window.history.back();
    }

    function printPage() {
    window.print();
    }

    function donePage(){
        window.location.href = `done_task`;
    }
</script>
{%endblock contentside %}

status/templates/documents/confirm_person.html
{% extends "pages/sidebar.html" %}
{% load i18n %}
{%block titleside%}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
    crossorigin="anonymous">
<title>{{task_name}}</title>
<style>
    .grid-container {
        display: grid;
        grid-template-columns: repeat(auto-fill,  1fr);
        gap: 10px;
    }
    .grid-item {
        background-color: #f0f0f0;
        padding: 10px;
        border: 3px solid #0a0a0a;
        text-align: center;
    }
    .column {
    max-width: 100%;
}

    .show{
        width:100%;
        border: 1px solid #ccc;
        display: grid;
        grid-template-columns: repeat(9, 1fr);

    }
    .first{
        padding: 10px;
        border: 1px solid #ccc;
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 10px;
    }
    #dataf{
        width :100%;
        border:1px solid #000;
        padding :10px;
    }
    #datan{
        width :15vw;
        border:1px solid #000;
        padding :10px;
    }
    #data{
        width :8vw;
        border:1px solid #000;
        padding :10px;
    }

    #dataf *{
        margin:10px;
    }

    #datan *{
        margin:10px;
    }

    #data *{
        margin:10px;
    }
</style>
{%endblock titleside %}

{%block contentside %}
    <div class="column">
    <p>{% trans "welcome"%} {{person_name}}</p>
    <form method="POST" style=" overflow :auto;  max-width:100%; width:95%;  padding: 10px; border: 1px solid #ccc;display: grid; grid-template-columns: repeat(1, 1fr);gap: 10px;" enctype="multipart/form-data">
        {%csrf_token%}

    <div class = "column">
        <div class="first">
            <div id="dataf" class = "col-12">{% trans "place of issue"%} :  {{person.place_of_issue}} </div>
            <div id="dataf" class = "col-12">{% trans "number of issue"%} :  {{person.number_of_issue}} </div>
        </div>
        <div class="show" >
            <div id="datan" class = "col-12 row-2"><div class = "row"> {% trans "name"%}  </div> <div class = "row"> {% trans "national number"%} </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {% trans "sur name"%} </div> <div class = "row">  </div></div>
            <div id="datan" class = "col-12 row-2"><div class = "row"> {% trans "dad name"%} </div> <div class = "row"> {% trans "national number"%} </div></div>
            <div id="datan" class = "col-12 row-2"><div class = "row"> {% trans "mom name"%} </div> <div class = "row"> {% trans "national number"%} </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {% trans "date and"%}  </div> <div class = "row"> {% trans "place birth"%} </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {% trans "religion"%} </div> <div class = "row">  </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {% trans "gender"%} </div> <div class = "row">  </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {% trans "status"%} </div> <div class = "row">  </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {% trans "date issue"%} </div> <div class = "row">   </div></div>
        </div>
        <div class="show">
            <div id="datan" class = "col-12 row-2"><div class = "row"> {{person.first_name}} </div> <div class = "row">{{person.national_num}}</div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {{person.last_name}} </div> <div class = "row"></div></div>
            <div id="datan" class = "col-12 row-2"><div class = "row"> {{person.dad_name}}</div> <div class = "row">{{person.national_dad}}</div></div>
            <div id="datan" class = "col-12 row-2"><div class = "row"> {{person.mom_name}} </div> <div class = "row">{{person.national_mom}}</div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {{person.birth_place}}  </div><div class = "row">{{person.birth_date|date:"y-m-d"}} </div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {{person.religion}} </div><div class = "row"></div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {{person.gender}} </div><div class = "row"></div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {{person.status}} </div><div class = "row"></div></div>
            <div id="data" class = "col-12 row-2"><div class = "row"> {{person.date_of_issue}} </div><div class = "row"></div></div>
        </div>
        {% if event != False %}
        <div class="first">
            <div id="data" class = "col-12">{% trans "place of dead"%} :  {{event.place_of_event}} </div>
            <div id="data" class = "col-12">{% trans "date of dead"%} :  {{event.date_of_event}} </div>
        </div>
        {% endif %}
    </div>
</form>
{% if employee.is_employee %}
<button style="margin: 1%;" onclick="donePage()"> {{task_name}} {% trans "is done"%}</button>
<button onclick="printPage()">{% trans "print"%} {{task_name}}</button>
{% else %}
<a  style="margin: 1%;" href="{% url 'documents:insert_task' %}" class="btn btn-primary">{% trans "get"%} {{task_name}}</a>
{% endif %}
<button onclick="goBack()">{% trans "Cancel"%}</button>

    </div>

<script>
    function goBack() {
        window.history.back();
    }
    function printPage() {
        window.print();
    }
    function donePage(){
        window.location.href = `done_task`;
    }
</script>
{%endblock contentside %}

status/templates/documents/note.html
{% extends "pages/sidebar.html" %}
{% load i18n %}
{%block titleside%}
    <title>{{task_name}}</title>
{% endblock titleside %}
{% block contentside %}
{{error}}
<div style="width: fit-content;  margin-top: 15%;">
    <div class="card" style="width:100% ; border-radius: 5%; background: rgb(79, 229, 240); margin-left: 35%; margin-top: 35%;">
        <div class="card-body" style="width: auto ;">
            <div style="display: flex; ">
                <h5 class="card-title"></h5>
            </div>
            <form method="POST">
                {%csrf_token%}
                <div style="padding: 15px;">{{form}} </div>
                <div onclick="nobeback()">
                    <input type="submit" value="{{task_name}}" style="margin: 15px; align-items: center;" >
                <button onclick="goBack()">{% trans "Cancel"%}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>

    function goBack() {
        window.history.back();
    }
    function nobeback(){
        history.go(-2);
        window.onpopstate = function(event) {
            if (event.state) {
                window.location.href = event.state;
            } else {
                window.location.href = "main.html";
            }
        };

    }

</script>
{% endblock contentside%}

status/templates/documents/review_task.html
{% extends "pages/sidebar.html" %}
{% load i18n %}
{%block titleside%}
    <title>{{task_name}}</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% endblock titleside %}


{% block contentside %}

<div class="documents-container">
    <div class="column">
    <div class="card"
    data-code="{{ document.code }}"
        style="border: 1px solid #ccc; margin: 10px; padding: 10px; cursor: pointer;">
        <h3>{% trans "document name"%} : {{ document.name }}</h3>
        <h3>{% trans "code"%} : {{ document.code }}</h3>
        <h3>{% trans "national ID of the Applicant"%} : {{ document.person_national_num }}</h3>
        {% if  document.second_national_num  %}
            <h3>{% trans "national ID of the Dependent"%} : {{ document.second_national_num }}</h3>
        {% endif %}
        <h3>date : {{ document.document_date }}</h3>
        {% if document.done %}
        <h3> {% trans "document done"%}</h3>
        {% elif document.viewed %}
        <h3> {% trans "document rejected"%}</h3>
        {% else %}
        <h3> {% trans "document pending"%}</h3>
        {% endif %}
        <h3 ><textarea name=" notes : " id="" cols="40" rows="6" readonly>{{ document.notes }}</textarea></h3>
        {% if not document.done %}
        {% if emperson.is_employee %}
        <div style="margin: 2px;"><a href="{%url 'documents:insert_document'%}" class="btn btn-primary">{% trans "check information"%}</a></div>
        <div style="margin: 2px;"><a href="{%url 'documents:refuse_with_note'%}" class="btn btn-primary">{% trans "refuse with note"%}</a></div>
        {% else %}
        <div style="margin: 2px;"><a href="{% url 'documents:send_notes'%}" class="btn btn-primary">{% trans "add note"%}</a></div>
        <div style="margin: 2px;"><a href="{% url 'documents:delete_document'%}" class="btn btn-primary">{% trans "Delete"%}</a></div>
        {% endif %}
        {% endif %}

    </div>
</div>
<button onclick="goBack()">{% trans "Cancel"%}</button>
</div>
    <script>
        function goBack() {
            window.history.back();
        }
        </script>
{% endblock contentside%}